### ISSUE TITLE
Upload the code of the demo instead of binary files for Windows

### ISSUE THREAD

**Issue by SuperFola** [Feldrise/FeldEngineFirstCode#2]
I can not test, I am under Linux Mint :/

**Comment by Feldrise** [comment]
Hello ^^

This project is completely abandoned and very old. Indeed it was not finished at all...
However if you still want to try I'll be able to upload code of demo in two weeks beceause I don't have any access to my PC yet :wink:

**Comment by Feldrise** [comment]
Actually, the code of all demos are the main, so you should checkout to previous version to get previous demo. I'll create tag when I'll have time ^^

**Comment by SuperFola** [comment]
Oh OK, no rush, I'll play hide and seek with those commits then c:
